sudo: required
language: ruby
rvm:
- 2.2.1
addons:
  hosts:
    - packer.hackathon.schibsted.io
before_install:
- openssl aes-256-cbc -K $encrypted_cb1cf17b1339_key -iv $encrypted_cb1cf17b1339_iv
  -in cert.pem.enc -out cert.pem -d
- sudo apt-get install nslookup
- sudo echo "$(nslookup packer.hackathon.schibsted.io  | grep -A10 answer | grep Address | cut -d ' ' -f2 | head -1) packer.hackathon.schibsted.io" >> /etc/hosts
- cat /etc/hosts
after_success:
- export packer_host=$(dig +short packer.hackathon.schibsted.io A)
- chmod 600 cert.pem
- rsync -a -arvce "ssh -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no " . packer@packer.hackathon.schibsted.io:/tmp/${TRAVIS_BUILD_ID}
- ssh -t -t -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no packer@packer.hackathon.schibsted.io "${TRAVIS_BUILD_ID}"
