language: ruby
rvm:
- 2.2.1
before_install:
- openssl aes-256-cbc -K $encrypted_cb1cf17b1339_key -iv $encrypted_cb1cf17b1339_iv
  -in cert.pem.enc -out cert.pem -d
after_success:
- chmod 600 cert.pem
- rsync  -a  -arvce "ssh -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no " . packer@packer.hackathon.schibsted.io:/tmp/${TRAVIS_BUILD_ID}
- sleep 1
- ssh -t -t -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no packer@packer.hackathon.schibsted.io "${TRAVIS_BUILD_ID}"
